In [123]:
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import sqlite3
import sqlalchemy as sqla
import re


In [4]:
import json

obj = """
{"name": "Wes",
"places_lived": ["United States", "Spain", "Germany"],
"pet": null,
"siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
{"name": "Katie", "age": 38,
"pets": ["Sixes", "Stache", "Cisco"]}]

}
"""

result = json.loads(obj)

result



{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [8]:
import requests

url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
    
resp = requests.get(url)

data = resp.json()

issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    45014                        TYP: type excel util module   
1    45013  BUG: `pandas/tests/arrays/floating/test_constr...   
2    45012  Set correct missing value indicator in astype ...   
3    45009  DEPR: special-cased downcasting in DataFrame.w...   
4    45008                        BLD: remove MSVC workaround   
5    45007                    PERF: DataFrame(pytorch_tensor)   
6    45006                    ENH: Implement Index.__invert__   
7    45005  REGR: DataFrame.shift with periods>len(columns...   
8    45004       BUG: Sparse[bool] type allows any fill_value   
9    45003  ENH: Allow passing a function to the `keep` pa...   
10   45002          PERF/CLN: avoid potential copies in ravel   
11   45001                fix column_arrays for array manager   
12   44998    CLN: follow-ups, whatsnew notes, use tm.get_obj   
13   44996  QST: Why is resampling with rule='7d' differen...   
14   44995  TST: backwards compatible test for reading jso...   
15   44994  CI: Test experimental data manager failing due...   
16   44993  BUG: Int64Index doesn't show when importing fr...   
17   44992  BUG: `DataFrameGroupBy.value_counts()` fails i...   
18   44987  DOC: Removed overview CONTRIBUTING file and it...   
19   44985  DOC: broken "Test-driven development/code writ...   
20   44980   CI: Builds failing in ``pandas.show_versions()``   
21   44978  BUG: `shift` with large `periods` creates mulf...   
22   44977  BUG: groupby.transform calls the user function...   
23   44976  DOC: to_parquet state that path can start with...   
24   44974   BUG: NDArrayBackedExtensionArray.transpose, copy   
25   44972  WIP: CI: Pameterize locale tests specifically ...   
26   44967                    CI: Add mambaforge to ci builds   
27   44966  BUILD: Cannot import and use pandas for python...   
28   44965  BUG: Apply pd.get_dummies() on string type col...   
29   44963  BUG: ImportError due to missing symbol "_ZTINS...   

                                               labels state  
0   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2   [{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
3   [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
4   [{'id': 57186974, 'node_id': 'MDU6TGFiZWw1NzE4...  open  
5   [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
6   [{'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMj...  open  
7   [{'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5...  open  
8   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
9   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
10  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
11  [{'id': 49379259, 'node_id': 'MDU6TGFiZWw0OTM3...  open  
12  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
13  [{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0...  open  
14  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
15  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
19  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
20  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
24  [{'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5...  open  
25  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
26  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
27  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
28  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
29  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open

In [6]:
arr = np.array([1.1,2.1,3.1,4.1,5.1,6.1,7.1,8.1], dtype=np.float64)

arr2 = np.array([1,2,3,4,5,6,7,8], dtype=np.int32)

arr3 = arr.astype(arr2.dtype)

arr3




array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
arr = np.array([[1.1,2.1,3.1,4.1],[5.1,6.1,7.1,8.1]])

a = arr[0]

a*4

arr



array([[1.1, 2.1, 3.1, 4.1],
       [5.1, 6.1, 7.1, 8.1]])

In [50]:
arr = np.arange(10).reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
arr = np.array([[1,-2,-3,4,5],[6,7,-8,-9,3]])

names = np.array(['orayt','pogi'])
b = names == 'pogi'


In [15]:
mask = (names == 'pogi') | (names == 'orayt')
mask

array([ True,  True])

In [103]:
arr[:,2] = 0
arr

array([[ 1, -2,  0,  4,  5],
       [ 6,  7,  0, -9,  3]])

In [113]:
arr =np.zeros((10,6))
for i in range(10):
    arr[i] = i
    
arr

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9.]])

In [121]:
sec = arr[[4,6,8,9]]
sec 

array([[4., 4., 0., 4., 4., 4.],
       [6., 6., 6., 6., 6., 0.],
       [8., 8., 8., 0., 8., 8.],
       [9., 0., 9., 9., 9., 9.]])

In [132]:
arr = np.arange(10).reshape(5,2)
arr.swapaxes

AxisError: axis2: axis 2 is out of bounds for array of dimension 2

In [143]:
arr = np.array([[[0., 0., 0., 0., 0., 0.],[1., 1., 1., 1., 1., 1.]],[[2., 2., 2., 2., 2., 2.],[3., 3., 3., 3., 3., 3.]],[[4., 4., 4., 4., 4., 4.],[5., 5., 5., 5., 5., 5.]]])
arr

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]],

       [[2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.]],

       [[4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.]]])

In [142]:
arr.transpose((2,1,0))

array([[[0., 2., 4.],
        [1., 3., 5.]],

       [[0., 2., 4.],
        [1., 3., 5.]],

       [[0., 2., 4.],
        [1., 3., 5.]],

       [[0., 2., 4.],
        [1., 3., 5.]],

       [[0., 2., 4.],
        [1., 3., 5.]],

       [[0., 2., 4.],
        [1., 3., 5.]]])

In [17]:
points = np.arange(10)
x , y = np.meshgrid(points,points)

flattened = np.array([val for arr in x for val in arr ])
flattened

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
       6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
       8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
np.sum(y)

450

In [84]:
obj2 = pd.Series(np.arange(5), index=['d', 'b', 'a', 'c','x'])
obj2

d    0
b    1
a    2
c    3
x    4
dtype: int32

In [87]:
obj2['b']

1

In [50]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index=['b','c','a'], columns=['b','c','a'])
df



b  c  a
b  1  2  3
c  4  5  6
a  7  8  9

In [51]:
df.column = ['a','b','c','d']
df

<ipython-input-51-c6e6c4f1b090>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.column = ['a','b','c','d']


b  c  a
b  1  2  3
c  4  5  6
a  7  8  9

In [43]:
o = df.values
o.dtype

dtype('float64')

In [52]:
df2 = df.reindex(['x','y','z'], axis=1, method='ffill')

ValueError: index must be monotonic increasing or decreasing

In [75]:
df3 = df.copy()

In [96]:
df.pct_change?

In [23]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [79]:
df = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]}, index=['b','c','a'])
df['bobo'] = [1,2,3]
states = ['Texas', 'Utah', 'California']
df.loc[['x','y','z','w'], states]

KeyError: "None of [Index(['x', 'y', 'z', 'w'], dtype='object')] are in the [index]"

In [69]:

df3 = df.reindex(['c','d','b','a'], axis=1)

df3

c   d  b  a
b  7 NaN  4  1
c  8 NaN  5  2
a  9 NaN  6  3

In [80]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],columns=['Ohio', 'Texas', 'California'])
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['b'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [4]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [8]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [6]:
ser = pd.Series(np.arange(3.))
ser


0    0.0
1    1.0
2    2.0
dtype: float64

In [9]:
ser.iloc[-1]

2.0

In [11]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [4]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [8]:
df.reindex(columns = ['two','one','three'])

two   one  three
a  NaN  1.40    NaN
b -4.5  7.10    NaN
c  NaN   NaN    NaN
d -1.3  0.75    NaN

In [10]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
unique_vals

0    c
1    b
2    a
dtype: object

In [11]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [7]:
ser = pd.Series([np.nan, 'a',np.nan, 'c', 'a'])

ser[ser.notnull()]


1    a
3    c
4    a
dtype: object

In [66]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])
data.loc[:'Utah','two'] = np.nan

data

one   two  three  four
Ohio        0   NaN      2     3
Colorado    4   NaN      6     7
Utah        8   NaN     10    11
New York   12  13.0     14    15

In [96]:
data.loc[:,'three'] = np.nan

data.dropna(thresh=2)

one   two  three  four
Ohio        0   NaN    NaN     3
Colorado    4   NaN    NaN     7
Utah        8   NaN    NaN    11
New York   12  13.0    NaN    15

In [93]:
data.dropna(thresh=2)

one   two  three  four
Ohio        0   NaN    NaN     3
Colorado    4   NaN    NaN     7
Utah        8   NaN    NaN    11
New York   12  13.0    NaN    15

In [67]:
df = pd.DataFrame([[1,2,3],[4,5,6],[1,9,5]], index=['b','c','a'], columns=['b','c','a'])

df


b  c  a
b  1  2  3
c  4  5  6
a  1  9  5

In [69]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [7]:
df = pd.DataFrame([[1,2,3],[4,5,6],[1,9,5]], index=['boo','cat','aurayt'], columns=['b','c','a'])

df2 = df.rename(index = str.title, columns = str.upper)

df2

B  C  A
Boo     1  2  3
Cat     4  5  6
Aurayt  1  9  5

In [13]:
df2[np.abs(df2) > 3] = np.sign(df2) * 3

df2

SyntaxError: can't assign to function call (<ipython-input-13-9e958a0c1c5f>, line 1)

In [17]:
rn = np.random.permutation(3)

df2.take(rn, axis = 1)

A  B  C
Boo     3  1  2
Cat     3  3  3
Aurayt  3  1  3

In [34]:
df.sample(n=6, replace=True, axis=1)

c  b  a  b  c  c
boo     2  1  3  1  2  2
cat     5  4  6  4  5  5
aurayt  9  1  5  1  9  9

In [103]:
moviedat = pd.read_table('pfda_files/datasets/movielens/movies.dat', engine='python', sep = '::', names=['Number', 'Movie','Genre'])
moviedat.head()

Number                               Movie                         Genre
0       1                    Toy Story (1995)   Animation|Children's|Comedy
1       2                      Jumanji (1995)  Adventure|Children's|Fantasy
2       3             Grumpier Old Men (1995)                Comedy|Romance
3       4            Waiting to Exhale (1995)                  Comedy|Drama
4       5  Father of the Bride Part II (1995)                        Comedy

In [109]:
titles = []
for movie in moviedat['Genre']:
    movies = movie.split('|')
    titles.extend(movies)
    
genres = pd.unique(titles)

In [115]:
zeromat = np.zeros((len(moviedat),len(unique_genres)))
dummies = pd.DataFrame(zeromat, columns=genres)

for i, gen in enumerate(moviedat.Genre):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1
    
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           1.0         1.0     1.0        0.0      0.0      0.0    0.0   
1           0.0         1.0     0.0        1.0      1.0      0.0    0.0   
2           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
3           0.0         0.0     1.0        0.0      0.0      0.0    1.0   
4           0.0         0.0     1.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    1.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       1.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [99]:
df = pd.DataFrame(np.random.randn(7, 3))
df


0         1         2
0  0.725816  0.128692 -0.033743
1 -0.757960  0.468389  0.718968
2  1.688220 -0.536943  1.110858
3  0.669280 -0.054082  1.894773
4 -1.387293 -0.407150 -0.683452
5  1.144134  0.269931  0.124507
6 -0.428237 -0.377343  0.616281

In [100]:
df.iloc[:2,1] = np.nan
df.iloc[:4,2] = np.nan

df

0         1         2
0  0.725816       NaN       NaN
1 -0.757960       NaN       NaN
2  1.688220 -0.536943       NaN
3  0.669280 -0.054082       NaN
4 -1.387293 -0.407150 -0.683452
5  1.144134  0.269931  0.124507
6 -0.428237 -0.377343  0.616281

In [102]:
df.dropna(thresh=2)

0         1         2
2  1.688220 -0.536943       NaN
3  0.669280 -0.054082       NaN
4 -1.387293 -0.407150 -0.683452
5  1.144134  0.269931  0.124507
6 -0.428237 -0.377343  0.616281

In [ ]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""



In [117]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com','Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [131]:
pattern = '([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

matches = data.str.match(pattern, flags=re.IGNORECASE)

matches.str[0]

AttributeError: Can only use .str accessor with string values!

AttributeError: Can only use .str accessor with string values!